name: Release
on: 
  workflow_dispatch:
  push:
    tags: '**'

permissions:
  contents: write
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
    
jobs:
  build:
    name: build and push docker image
    runs-on: ubuntu-latest
    outputs: 
      build_tag: ${{env.GIT_TAG_NAME}}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_IO_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: version=${{ env.GIT_TAG_NAME || '7.16.3'}}
          tags: ${{ env.REGISTRY }}/${{github.repository}}:${{ env.GIT_TAG_NAME || '7.16.3' }}
          push: true
          
  release:
    name: github release
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.build_tag }}
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Update elasticstack to ${{ needs.build.outputs.build_tag }}

          
