on: 
  push:
    tags: '**'

    
jobs:
  release:
    name: build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_USER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: version=${{ env.GIT_TAG_NAME }}
          push: false

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Update elasticstack to ${{ env.GIT_TAG_NAME }}

      - name: Send mail
        uses: dawidd6/action-send-mail@v3.4.1
        with:
          server_address: ${{secrets.MAIL_HOST}}
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Action build ElasticSearch ${{ env.GIT_TAG_NAME }}
          to: ${{secrets.MAIL_TO}}
          from: Github Action           
          secure: true
          body: "Build job of https://github.com/${{github.repository}}/releases completed successfully! New Version: ${{ env.GIT_TAG_NAME }}"
          reply_to: ${{secrets.MAIL_REPLAY_TO}}
          ignore_cert: true
          